### ISSUE TITLE
No support for negative numbers

### ISSUE THREAD

**Issue by mikolajefento** [notKamui/Keval#35]
Running `keval()` on single negative number results in exception `KevalInvalidExpressionException`

The `neg()` function seems to work in those situations but it would be nice to have support for negation via minus operator.

Tested on: Android
keval version: `0.9.0`
minimal reproducible example: `"-1".keval()`

**Comment by notKamui** [comment]
Yup, this is not a bug, as for now, Keval doesn't support (postfix) unary operators. However it is explicitly written in the documentation.

This is something I was planning to do for a long, but haven't quite had the time to do it. 

Another way to work around this issue is to do `0 - 1` to get -1, for example. I agree this is not ideal though.

Note that to support unary operators, the whole engine has to be rewritten from scratch with a proper grammar instead of the shunting-yard algorithm.

**Comment by notKamui** [comment]
@mikolajefento all done (after quite a bit of time)
