### ISSUE TITLE
Unary minus operator (negation)

### ISSUE THREAD

**Issue by sosauce** [notKamui/Keval#36]
Hello! So I use ur library in one of my app cuz its very cool and simple, are you still working on negative numbers within the .keval() method ?

**Comment by notKamui** [comment]
Hello ! I am very sorry to say that I currently don't have that much time to work on this library because of work. However, I would gladly accept your help in the form of a PR !

For the time being, I know it's not most convenient, but you can obtain what you want by either doing `neg(yourNumber)` or `0 - yourNumber`.

I really should find the time to improve this.

**Comment by sosauce** [comment]
Okay thanks !

**Comment by notKamui** [comment]
Well @sosauce I am trying some things ; you can check it out on this branch: https://github.com/notKamui/Keval/tree/grammar-engine

It's mostly working with a few bugs, and basically broken validation (it doesn't tell you what is wrong if the expression is invalid). But it's on good tracks. It's probably gonna be okay in a week or so.

Stay tuned.

**Comment by sosauce** [comment]
Great ! I'm busy for now will test when avaible, how do I use the grammar branch, or will the changes be auto applied to the library ?

**Comment by notKamui** [comment]
@sosauce ah you'll have to wait for me to publish it.

i was just notifying you about it, but it's not usable in the current state. 

again, it's probably gonna be good by the end of the week.

**Comment by sosauce** [comment]
Ahah don't worry take ur time ! I'm real busy with school / personnal things atm so i'm not really working on my app rn

**Comment by notKamui** [comment]
@sosauce all done !
